# Generated by Django 4.0 on 2022-06-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512, unique=True)),
                ('rid', models.CharField(blank=True, default='', max_length=512)),
                ('need_fix', models.BooleanField(default=False)),
                ('STR', models.IntegerField(blank=True, default=0, null=True)),
                ('DEX', models.IntegerField(blank=True, default=0, null=True)),
                ('CON', models.IntegerField(blank=True, default=0, null=True)),
                ('INT', models.IntegerField(blank=True, default=0, null=True)),
                ('WIS', models.IntegerField(blank=True, default=0, null=True)),
                ('CHA', models.IntegerField(blank=True, default=0, null=True)),
                ('base_STR', models.IntegerField(blank=True, default=0, null=True)),
                ('base_DEX', models.IntegerField(blank=True, default=0, null=True)),
                ('base_CON', models.IntegerField(blank=True, default=0, null=True)),
                ('base_INT', models.IntegerField(blank=True, default=0, null=True)),
                ('base_WIS', models.IntegerField(blank=True, default=0, null=True)),
                ('base_CHA', models.IntegerField(blank=True, default=0, null=True)),
                ('STR_racial_mod', models.IntegerField(blank=True, default=0)),
                ('DEX_racial_mod', models.IntegerField(blank=True, default=0)),
                ('CON_racial_mod', models.IntegerField(blank=True, default=0)),
                ('INT_racial_mod', models.IntegerField(blank=True, default=0)),
                ('WIS_racial_mod', models.IntegerField(blank=True, default=0)),
                ('CHA_racial_mod', models.IntegerField(blank=True, default=0)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('age', models.IntegerField(blank=True, default=25)),
                ('LtoC', models.IntegerField(blank=True, default=0)),
                ('GtoE', models.IntegerField(blank=True, default=0)),
                ('xp_value', models.IntegerField(blank=True, default=0)),
                ('CR', models.IntegerField(blank=True, default=1)),
                ('speed', models.IntegerField(blank=True, default=30)),
                ('AC', models.IntegerField(blank=True, default=0)),
                ('touch_AC', models.IntegerField(blank=True, default=0)),
                ('flatfooted_AC', models.IntegerField(blank=True, default=0)),
                ('AC_details', models.TextField(blank=True, default='', max_length=1024)),
                ('hp', models.IntegerField(blank=True, default=0)),
                ('hp_formula', models.TextField(blank=True, default='', max_length=1024)),
                ('fort', models.IntegerField(blank=True, default=0)),
                ('ref', models.IntegerField(blank=True, default=0)),
                ('will', models.IntegerField(blank=True, default=0)),
                ('saves_details', models.TextField(blank=True, default='', max_length=1024)),
                ('BAB', models.IntegerField(blank=True, default=0)),
                ('CMB', models.IntegerField(blank=True, default=0)),
                ('CMD', models.IntegerField(blank=True, default=0)),
                ('during_combat_tactics', models.TextField(blank=True, default='', max_length=1024)),
                ('morale_tactics', models.TextField(blank=True, default='', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PathfinderClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('STR_favorite', models.IntegerField(blank=True, default=0)),
                ('DEX_favorite', models.IntegerField(blank=True, default=0)),
                ('CON_favorite', models.IntegerField(blank=True, default=0)),
                ('INT_favorite', models.IntegerField(blank=True, default=0)),
                ('WIS_favorite', models.IntegerField(blank=True, default=0)),
                ('CHA_favorite', models.IntegerField(blank=True, default=0)),
                ('CHOICE_racial_mod', models.IntegerField(blank=True, default=0)),
                ('bonus_feat', models.IntegerField(blank=True, default=0)),
                ('bonus_skill', models.IntegerField(blank=True, default=0)),
                ('is_npc_class', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PathfinderRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('variant', models.CharField(blank=True, default='', max_length=512)),
                ('STR_racial_mod', models.IntegerField(blank=True, default=0, verbose_name='STR')),
                ('DEX_racial_mod', models.IntegerField(blank=True, default=0, verbose_name='DEX')),
                ('CON_racial_mod', models.IntegerField(blank=True, default=0, verbose_name='CON')),
                ('INT_racial_mod', models.IntegerField(blank=True, default=0, verbose_name='INT')),
                ('WIS_racial_mod', models.IntegerField(blank=True, default=0, verbose_name='WIS')),
                ('CHA_racial_mod', models.IntegerField(blank=True, default=0, verbose_name='CHA')),
                ('CHOICE_racial_mod', models.IntegerField(blank=True, default=0)),
                ('bonus_racial_feat', models.IntegerField(blank=True, default=0)),
                ('bonus_racial_skill', models.IntegerField(blank=True, default=0)),
                ('size', models.CharField(blank=True, default='Medium', max_length=30)),
                ('category', models.CharField(blank=True, default='Humanoid', max_length=30)),
                ('number_of_favorite_classes', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PathfinderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('is_trained_only', models.BooleanField(default=False)),
                ('is_wildcard', models.BooleanField(default=False)),
                ('ability', models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], default='INT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PathfinderClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfindercharacter')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderclass')),
            ],
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.pathfinderrace'),
        ),
    ]
