# Generated by Django 4.0 on 2022-06-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('variant', models.CharField(blank=True, max_length=512)),
                ('STR_racial_mod', models.IntegerField(blank=True, default=0)),
                ('DEX_racial_mod', models.IntegerField(blank=True, default=0)),
                ('CON_racial_mod', models.IntegerField(blank=True, default=0)),
                ('INT_racial_mod', models.IntegerField(blank=True, default=0)),
                ('WIS_racial_mod', models.IntegerField(blank=True, default=0)),
                ('CHA_racial_mod', models.IntegerField(blank=True, default=0)),
                ('CHOICE_racial_mod', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
