# Generated by Django 4.0 on 2022-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_pathfinderrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderrace',
            name='bonus_racial_feat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfinderrace',
            name='bonus_racial_skill',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
