# Generated by Django 4.0 on 2022-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_pathfinderrace_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PathfinderClassLevel',
            new_name='PathfinderLevel',
        ),
        migrations.RemoveField(
            model_name='pathfinderclass',
            name='CHOICE_racial_mod',
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='base_attack_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='base_fort',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='base_ref',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='base_will',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
