# Generated by Django 4.0 on 2022-06-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_pathfinderrace_bonus_racial_feat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.pathfinderrace'),
        ),
    ]
