# Generated by Django 4.0 on 2022-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_rename_pathfinderclasslevel_pathfinderlevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('is_fighter_feat', models.BooleanField(default=False)),
                ('prerequisites', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
    ]
