# Generated by Django 4.0 on 2022-06-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_pathfinderfeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathfindercharacter',
            options={'verbose_name': 'Pathfinder Character'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderclass',
            options={'verbose_name': 'Pathfinder Class', 'verbose_name_plural': 'Pathfinder Classes'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderfeat',
            options={'verbose_name': 'Pathfinder Feat'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderlevel',
            options={'verbose_name': 'Pathfinder Level'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderrace',
            options={'verbose_name': 'Pathfinder Race'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderskill',
            options={'verbose_name': 'Pathfinder Skill'},
        ),
    ]
