# Generated by Django 4.0 on 2022-06-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_pathfindercharacter_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindercharacter',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
