# Generated by Django 4.0 on 2022-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_alter_pathfindercharacter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='hit_dice',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='skill_ranks_per_level',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
