# Generated by Django 4.0 on 2022-06-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_alter_pathfindercharacter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfindercharacter',
            name='name',
            field=models.CharField(default='', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='pathfindercharacter',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='CHA_racial_mod',
            field=models.IntegerField(blank=True, default=0, verbose_name='CHA'),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='CON_racial_mod',
            field=models.IntegerField(blank=True, default=0, verbose_name='CON'),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='DEX_racial_mod',
            field=models.IntegerField(blank=True, default=0, verbose_name='DEX'),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='INT_racial_mod',
            field=models.IntegerField(blank=True, default=0, verbose_name='INT'),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='STR_racial_mod',
            field=models.IntegerField(blank=True, default=0, verbose_name='STR'),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='WIS_racial_mod',
            field=models.IntegerField(blank=True, default=0, verbose_name='WIS'),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='pathfinderrace',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
