# Generated by Django 4.0 on 2022-06-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_pathfinderclass_hit_dice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathfinderclass',
            old_name='hit_dice',
            new_name='hit_die',
        ),
    ]
