# Generated by Django 4.0 on 2022-06-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_alter_pathfindercharacter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('STR_favorite', models.IntegerField(blank=True, default=0)),
                ('DEX_favorite', models.IntegerField(blank=True, default=0)),
                ('CON_favorite', models.IntegerField(blank=True, default=0)),
                ('INT_favorite', models.IntegerField(blank=True, default=0)),
                ('WIS_favorite', models.IntegerField(blank=True, default=0)),
                ('CHA_favorite', models.IntegerField(blank=True, default=0)),
                ('CHOICE_racial_mod', models.IntegerField(blank=True, default=0)),
                ('bonus_feat', models.IntegerField(blank=True, default=0)),
                ('bonus_skill', models.IntegerField(blank=True, default=0)),
                ('is_npc_class', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PathfinderClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfindercharacter')),
                ('pclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderclass')),
            ],
        ),
    ]
