# Generated by Django 4.0 on 2022-06-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_rename_hit_dice_pathfinderclass_hit_die'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='AC_armor_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='AC_deflection_modifier',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='AC_misc_modifier',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='AC_natural_armor',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='AC_shield_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='AC_size_modifier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
