# Generated by Django 4.0 on 2022-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_rename_pclass_pathfinderclasslevel_character_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderrace',
            name='number_of_favorite_classes',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
