# Generated by Django 4.0 on 2022-06-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_pathfindercharacter_ac_armor_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('quality', models.CharField(blank=True, choices=[('std', 'Standard'), ('mwk', 'Masterwork')], default='std', max_length=64)),
                ('gp_price', models.PositiveIntegerField(default=0)),
                ('lbs_weight', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pathfinder Gear',
            },
        ),
        migrations.CreateModel(
            name='PathfinderWeapon',
            fields=[
                ('pathfindergear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.pathfindergear')),
                ('attack_bonus', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Pathfinder Weapon',
            },
            bases=('collector.pathfindergear',),
        ),
    ]
