# Generated by Django 4.0 on 2022-06-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_pathfinderrace_number_of_favorite_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathfinderclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderclasslevel',
            options={'verbose_name': 'ClassLevel', 'verbose_name_plural': 'ClassLevels'},
        ),
    ]
