# Generated by Django 4.0 on 2022-06-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_alter_pathfinderclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathfindercharacter',
            options={'verbose_name': 'Character'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderclasslevel',
            options={'verbose_name': 'Class-Level', 'verbose_name_plural': 'Class-Levels'},
        ),
        migrations.AlterModelOptions(
            name='pathfinderrace',
            options={'verbose_name': 'Race'},
        ),
    ]
