# Generated by Django 4.0 on 2022-06-09 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_pathfindergear_cp_price_pathfindergear_gp_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderArmor',
            fields=[
                ('pathfindergear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collector.pathfindergear')),
                ('AC_bonus', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Pathfinder Weapon',
            },
            bases=('collector.pathfindergear',),
        ),
    ]
