# Generated by Django 4.0 on 2022-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_alter_pathfindercharacter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclasslevel',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
