# Generated by Django 4.0 on 2022-06-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_pathfinderarmor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathfinderarmor',
            options={'verbose_name': 'Pathfinder Armor'},
        ),
    ]
