# Generated by Django 4.0 on 2022-06-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_alter_pathfinderarmor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindergear',
            name='qualifier',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
