# Generated by Django 4.0 on 2022-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_pathfinderclasslevel_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='CHA_racial_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='CON_racial_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='DEX_racial_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='INT_racial_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='STR_racial_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='WIS_racial_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
