# Generated by Django 4.0 on 2022-06-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_pathfindercharacter_cha_racial_mod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='CHA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='CON',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='DEX',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='INT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='STR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='WIS',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
