# Generated by Django 4.0 on 2022-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_pathfindergear_qualifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderarmor',
            name='arcane_spell_failure',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfinderarmor',
            name='armor_check_penalty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfinderarmor',
            name='max_dex_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
