# Generated by Django 4.0 on 2022-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_pathfinderspell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderspell',
            name='drawonic',
        ),
        migrations.AddField(
            model_name='pathfinderspell',
            name='draconic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='acid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='air',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='chaotic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='cold',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='curse',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='darkness',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='death',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='disease',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='earth',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='electricity',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='emotion',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='evil',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='fear',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='fire',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='force',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='good',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='language_dependent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='lawful',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='light',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='meditative',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='mind_affecting',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='mythic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='pain',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='poison',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='ruse',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='shadow',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='sonic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='water',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
