# Generated by Django 4.0 on 2022-06-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_remove_pathfinderspell_drawonic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderspell',
            name='short_desciption',
        ),
        migrations.AddField(
            model_name='pathfinderspell',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='description_formatted',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='full_text',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
    ]
