# Generated by Django 4.0 on 2022-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_remove_pathfinderspell_short_desciption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderspell',
            name='spell_level',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
