# Generated by Django 4.0 on 2022-06-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_alter_pathfinderspell_spell_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderspell',
            name='targets',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
