# Generated by Django 4.0 on 2022-06-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_alter_pathfinderspell_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderspell',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5120),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='description_formatted',
            field=models.TextField(blank=True, default='', max_length=5120),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='full_text',
            field=models.TextField(blank=True, default='', max_length=5120),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=5120),
        ),
    ]
