# Generated by Django 4.0 on 2022-06-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_alter_pathfinderspell_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderspell',
            name='spell_resistance',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
