# Generated by Django 4.0 on 2022-06-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_alter_pathfinderspell_sla_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderspell',
            name='full_text',
            field=models.TextField(blank=True, default='', max_length=8192),
        ),
    ]
