# Generated by Django 4.0 on 2022-06-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_alter_pathfinderspell_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderspell',
            name='haunt_statistics',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
