# Generated by Django 4.0 on 2022-06-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0032_alter_pathfinderspell_haunt_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderspell',
            name='haunt_statistics',
            field=models.TextField(blank=True, default='', max_length=6144),
        ),
    ]
