# Generated by Django 4.0 on 2022-06-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0033_alter_pathfinderspell_haunt_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='init',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='senses',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
