# Generated by Django 4.0 on 2022-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0035_alter_pathfinderspell_adept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='class_skills',
            field=models.TextField(blank=True, default=2048),
        ),
    ]
