# Generated by Django 4.0 on 2022-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0036_pathfinderclass_class_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderclass',
            name='class_skills',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
