# Generated by Django 4.0 on 2022-06-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0037_alter_pathfinderclass_class_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderrank',
            name='class_skill_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderlevel'),
        ),
        migrations.AddField(
            model_name='pathfinderrank',
            name='max',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
