# Generated by Django 4.0 on 2022-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0038_pathfinderrank_class_skill_as_pathfinderrank_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='total_skill_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
