# Generated by Django 4.0 on 2022-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0039_pathfindercharacter_total_skill_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='BAB_rate',
            field=models.CharField(choices=[('FBAB', 'Fast BAB'), ('MBAB', 'Medium BAB'), ('SBAB', 'Slow BAB')], default='MBAB', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='fort_rate',
            field=models.CharField(choices=[('GSAVE', 'Good Save'), ('BSAVE', 'Bad Save')], default='BSAVE', max_length=5),
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='ref_rate',
            field=models.CharField(choices=[('GSAVE', 'Good Save'), ('BSAVE', 'Bad Save')], default='BSAVE', max_length=5),
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='will_rate',
            field=models.CharField(choices=[('GSAVE', 'Good Save'), ('BSAVE', 'Bad Save')], default='BSAVE', max_length=5),
        ),
    ]
