# Generated by Django 4.0 on 2022-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0041_pathfindercharacter_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='base_gold',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfinderrace',
            name='starting_age_formula',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
