# Generated by Django 4.0 on 2022-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0042_pathfinderclass_base_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='player',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
