# Generated by Django 4.0 on 2022-06-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0048_pathfinderweapon_dmg_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderweapon',
            name='weapon_type',
            field=models.CharField(blank=True, default='B', max_length=1),
        ),
    ]
