# Generated by Django 4.0 on 2022-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0049_pathfinderweapon_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderweapon',
            name='weapon_type',
            field=models.CharField(blank=True, default='B', max_length=3),
        ),
    ]
