# Generated by Django 4.0 on 2022-06-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0051_pathfinderweapon_weapon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='base_age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
