# Generated by Django 4.0 on 2022-06-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0052_pathfinderclass_base_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='base_choice_racial_mod',
            field=models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('---', 'None')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='pathfinderskill',
            name='ability',
            field=models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('---', 'None')], default='INT', max_length=3),
        ),
    ]
