# Generated by Django 4.0 on 2022-06-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0053_pathfindercharacter_base_choice_racial_mod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='CHA_racial_mod',
        ),
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='CON_racial_mod',
        ),
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='DEX_racial_mod',
        ),
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='INT_racial_mod',
        ),
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='STR_racial_mod',
        ),
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='WIS_racial_mod',
        ),
    ]
