# Generated by Django 4.0 on 2022-06-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0054_remove_pathfindercharacter_cha_racial_mod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='base_hwmod',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
