# Generated by Django 4.0 on 2022-06-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0055_pathfindercharacter_base_hwmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='base_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
