# Generated by Django 4.0 on 2022-06-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0056_pathfindercharacter_base_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderrace',
            name='speed',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
