# Generated by Django 4.0 on 2022-06-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0057_pathfinderrace_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderclass',
            name='base_attack_bonus',
        ),
        migrations.RemoveField(
            model_name='pathfinderclass',
            name='base_fort',
        ),
        migrations.RemoveField(
            model_name='pathfinderclass',
            name='base_ref',
        ),
        migrations.RemoveField(
            model_name='pathfinderclass',
            name='base_will',
        ),
    ]
