# Generated by Django 4.0 on 2022-06-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0058_remove_pathfinderclass_base_attack_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.pathfindercharacter')),
                ('gear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.pathfindergear')),
            ],
            options={
                'verbose_name': 'Pathfinder Equipment',
            },
        ),
    ]
