# Generated by Django 4.0 on 2022-06-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0059_pathfinderequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderequipment',
            name='equipped',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
