# Generated by Django 4.0 on 2022-06-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0060_pathfinderequipment_equipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindergear',
            name='is_armor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pathfindergear',
            name='is_weapon',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
