# Generated by Django 4.0 on 2022-07-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0061_pathfindergear_is_armor_pathfindergear_is_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderSpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('is_senses', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True, default='', max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Pathfinder Special Abilities',
            },
        ),
    ]
