# Generated by Django 4.0 on 2022-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0062_pathfinderspecialability'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderrace',
            name='special_abilities',
            field=models.ManyToManyField(to='collector.PathfinderSpecialAbility'),
        ),
    ]
