# Generated by Django 4.0 on 2022-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0063_pathfinderrace_special_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderspecialability',
            name='is_abilities_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathfinderspecialability',
            name='is_defense_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathfinderspecialability',
            name='is_offense_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathfinderspecialability',
            name='is_skill_related',
            field=models.BooleanField(default=False),
        ),
    ]
