# Generated by Django 4.0 on 2022-07-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0064_pathfinderspecialability_is_abilities_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderspecialability',
            name='is_spell_like_abilities',
            field=models.BooleanField(default=False),
        ),
    ]
