# Generated by Django 4.0 on 2022-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0067_remove_pathfindergear_is_armor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindergear',
            name='is_armor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pathfindergear',
            name='is_weapon',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
