# Generated by Django 4.0 on 2022-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0068_pathfindergear_is_armor_pathfindergear_is_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='ranked_skills',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
