# Generated by Django 4.0 on 2022-07-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0069_pathfindercharacter_ranked_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderrank',
            name='total',
        ),
        migrations.AddField(
            model_name='pathfinderrank',
            name='ability_modifier',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
