# Generated by Django 4.0 on 2022-07-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0071_pathfinderspecialability_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderarmor',
            name='category',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
