# Generated by Django 4.0 on 2022-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0072_pathfinderarmor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='dm_notes',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
