# Generated by Django 4.0 on 2022-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0074_pathfinderlevel_deity_pathfinderlevel_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderlevel',
            name='favored_hit_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathfinderlevel',
            name='favored_skill_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
