# Generated by Django 4.0 on 2022-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0075_pathfinderlevel_favored_hit_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='current_xp',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
