# Generated by Django 4.0 on 2022-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0076_pathfindercharacter_current_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderrank',
            name='class_skill_bonus',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
