# Generated by Django 4.0 on 2022-07-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0077_pathfinderrank_class_skill_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderrank',
            name='details',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
