# Generated by Django 4.0 on 2022-07-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0079_pathfinderclass_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='is_spellcasting_class',
            field=models.BooleanField(default=False),
        ),
    ]
