# Generated by Django 4.0 on 2022-07-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0080_pathfinderclass_is_spellcasting_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderClassAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('is_senses', models.BooleanField(default=False)),
                ('is_skill_related', models.BooleanField(default=False)),
                ('is_feat_related', models.BooleanField(default=False)),
                ('is_offense_related', models.BooleanField(default=False)),
                ('is_defense_related', models.BooleanField(default=False)),
                ('is_abilities_bonus', models.BooleanField(default=False)),
                ('is_spell_like_abilities', models.BooleanField(default=False)),
                ('short_description', models.TextField(blank=True, default='', max_length=512)),
                ('formula', models.TextField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Pathfinder Class Abilities',
            },
        ),
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='race',
        ),
        migrations.CreateModel(
            name='PathfinderLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfindercharacter')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderrace')),
            ],
            options={
                'verbose_name': 'Pathfinder Legacy',
            },
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='class_abilities',
            field=models.ManyToManyField(to='collector.PathfinderClassAbility'),
        ),
    ]
