# Generated by Django 4.0 on 2022-07-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0082_pathfindercharacter_race'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PathfinderLegacy',
        ),
    ]
