# Generated by Django 4.0 on 2022-07-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0084_rename_base_cha_pathfindercharacter_volatile_cha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathfindercharacter',
            old_name='base_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='pathfindercharacter',
            old_name='base_weight',
            new_name='weight',
        ),
    ]
