# Generated by Django 4.0 on 2022-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0088_pathfindercharacter_feats'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderfeat',
            name='formula',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='pathfinderfeat',
            name='is_skill_related',
            field=models.BooleanField(default=False),
        ),
    ]
