# Generated by Django 4.0 on 2022-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0089_pathfinderfeat_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderfeat',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
