# Generated by Django 4.0 on 2022-07-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0090_pathfinderfeat_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderfeat',
            name='target',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
