# Generated by Django 4.0 on 2022-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0091_pathfinderfeat_target'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PathfinderClassAbility',
            new_name='PathfinderClassFeature',
        ),
        migrations.RemoveField(
            model_name='pathfinderclass',
            name='class_abilities',
        ),
        migrations.AddField(
            model_name='pathfinderclass',
            name='class_features',
            field=models.ManyToManyField(to='collector.PathfinderClassFeature'),
        ),
    ]
