# Generated by Django 4.0 on 2022-07-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0092_rename_pathfinderclassability_pathfinderclassfeature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathfinderclassfeature',
            options={'verbose_name_plural': 'Pathfinder Class Features'},
        ),
    ]
