# Generated by Django 4.0 on 2022-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0093_alter_pathfinderclassfeature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclassfeature',
            name='feature_type',
            field=models.CharField(choices=[('Ex', 'Extraordinary'), ('Su', 'Supernatural'), ('Sp', 'Spell Like Ability')], default='Ex', max_length=2),
        ),
    ]
