# Generated by Django 4.0 on 2022-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0094_pathfinderclassfeature_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderclassfeature',
            name='feature_type',
            field=models.CharField(choices=[('No', 'Normal'), ('Ex', 'Extraordinary'), ('Su', 'Supernatural'), ('Sp', 'Spell Like Ability')], default='No', max_length=2),
        ),
    ]
