# Generated by Django 4.0 on 2022-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0095_alter_pathfinderclassfeature_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclassfeature',
            name='is_armor_proficiencies',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='pathfinderclassfeature',
            name='is_weapon_proficiencies',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
