# Generated by Django 4.0 on 2022-07-14 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0096_pathfinderclassfeature_is_armor_proficiencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderclassfeature',
            name='is_armor_proficiencies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pathfinderclassfeature',
            name='is_weapon_proficiencies',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PathfinderClassAdvancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, default=0)),
                ('pathfinder_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderclass')),
            ],
            options={
                'verbose_name_plural': 'Pathfinder Class Advancement',
            },
        ),
    ]
