# Generated by Django 4.0 on 2022-07-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0097_alter_pathfinderclassfeature_is_armor_proficiencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderclass',
            name='class_features',
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='class_features',
            field=models.ManyToManyField(to='collector.PathfinderClassFeature'),
        ),
    ]
