# Generated by Django 4.0 on 2022-07-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0098_remove_pathfinderclass_class_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderclassadvancement',
            name='class_features',
            field=models.ManyToManyField(blank=True, to='collector.PathfinderClassFeature'),
        ),
    ]
