# Generated by Django 4.0 on 2022-07-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0099_alter_pathfinderclassadvancement_class_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_abilities_bonus',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_armor_proficiencies',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_defense_related',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_feat_related',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_offense_related',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_senses',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_skill_related',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_spell_like_abilities',
        ),
        migrations.RemoveField(
            model_name='pathfinderclassfeature',
            name='is_weapon_proficiencies',
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_0',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_1',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_2',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_3',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_4',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_5',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_6',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_7',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_8',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pathfinderclassadvancement',
            name='spd_9',
            field=models.CharField(blank=True, default='-', max_length=4),
        ),
    ]
