# Generated by Django 4.0 on 2022-07-14 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0100_remove_pathfinderclassfeature_is_abilities_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderCharacterFeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(blank=True, default='', max_length=256)),
                ('character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collector.pathfindercharacter')),
                ('feat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderfeat')),
            ],
            options={
                'verbose_name_plural': 'Pathfinder Character Feats',
            },
        ),
    ]
