# Generated by Django 4.0 on 2022-07-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0101_pathfindercharacterfeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfindercharacter',
            name='feats',
        ),
    ]
