# Generated by Django 4.0 on 2022-07-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0102_remove_pathfindercharacter_feats'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='volatile_money',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
