# Generated by Django 4.0 on 2022-07-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0103_pathfindercharacter_volatile_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='tcl',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
