# Generated by Django 4.0 on 2022-07-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0104_pathfindercharacter_tcl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='volatile_choice_main_ability',
            field=models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('---', 'None')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='pathfinderclass',
            name='BAB_rate',
            field=models.CharField(choices=[('FBAB', 'Fast'), ('MBAB', 'Medium'), ('SBAB', 'Slow')], default='MBAB', max_length=4),
        ),
        migrations.AlterField(
            model_name='pathfinderclass',
            name='fort_rate',
            field=models.CharField(choices=[('GSAVE', 'Good'), ('BSAVE', 'Bad')], default='BSAVE', max_length=5),
        ),
        migrations.AlterField(
            model_name='pathfinderclass',
            name='ref_rate',
            field=models.CharField(choices=[('GSAVE', 'Good'), ('BSAVE', 'Bad')], default='BSAVE', max_length=5),
        ),
        migrations.AlterField(
            model_name='pathfinderclass',
            name='will_rate',
            field=models.CharField(choices=[('GSAVE', 'Good'), ('BSAVE', 'Bad')], default='BSAVE', max_length=5),
        ),
    ]
