# Generated by Django 4.0 on 2022-07-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0105_pathfinderclass_volatile_choice_main_ability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathfinderclass',
            old_name='volatile_choice_main_ability',
            new_name='main_ability',
        ),
    ]
