# Generated by Django 4.0 on 2022-08-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0106_rename_volatile_choice_main_ability_pathfinderclass_main_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='homeland',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
