# Generated by Django 4.0 on 2022-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0107_pathfindercharacter_homeland'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderarmor',
            name='is_shield',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
