# Generated by Django 4.0 on 2022-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0108_pathfinderarmor_is_shield'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='volatile_age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
