# Generated by Django 4.0 on 2022-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0109_pathfindercharacter_volatile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderlevel',
            name='is_giving_skill_points',
        ),
        migrations.AlterField(
            model_name='pathfindercharacter',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
