# Generated by Django 4.0 on 2022-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0110_remove_pathfinderlevel_is_giving_skill_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='DR',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
