# Generated by Django 4.0 on 2022-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0111_pathfindercharacter_dr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathfindercharacter',
            old_name='fort',
            new_name='fortitude',
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='base_fortitude',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='base_reflex',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='base_will',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='fortitude_ability_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='init_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='reflex_ability_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='will_ability_mod',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
