# Generated by Django 4.0 on 2022-08-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0113_rename_ref_pathfindercharacter_reflex'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='armor_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='burrow_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='climb_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='fly_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pathfindercharacter',
            name='swim_speed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pathfindercharacter',
            name='speed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
