# Generated by Django 4.0 on 2022-08-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0114_pathfindercharacter_armor_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderarmor',
            name='speed_20',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='pathfinderarmor',
            name='speed_30',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
