# Generated by Django 4.0 on 2022-08-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0115_pathfinderarmor_speed_20_pathfinderarmor_speed_30'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathfinderSpellsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderlevel')),
                ('spells', models.ManyToManyField(to='collector.PathfinderSpell')),
            ],
            options={
                'verbose_name': 'Pathfinder Feat',
            },
        ),
    ]
