# Generated by Django 4.0 on 2022-08-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0116_pathfinderspellscollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderspellscollection',
            name='character_level',
        ),
    ]
