# Generated by Django 4.0 on 2022-08-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0117_remove_pathfinderspellscollection_character_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathfinderspellscollection',
            options={'verbose_name': 'Pathfinder Spells Collection'},
        ),
    ]
