# Generated by Django 4.0 on 2022-08-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0118_alter_pathfinderspellscollection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderlevel',
            name='spells_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderspellscollection'),
        ),
    ]
