# Generated by Django 4.0 on 2022-08-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0119_pathfinderlevel_spells_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderspellscollection',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
