# Generated by Django 4.0 on 2022-08-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0120_pathfinderspellscollection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderspellscollection',
            name='spells',
        ),
        migrations.AddField(
            model_name='pathfinderspell',
            name='spells_collection',
            field=models.ManyToManyField(to='collector.PathfinderSpellsCollection'),
        ),
    ]
