# Generated by Django 4.0 on 2022-08-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0121_remove_pathfinderspellscollection_spells_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathfinderlevel',
            name='spells_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.pathfinderspellscollection'),
        ),
        migrations.AlterField(
            model_name='pathfinderspell',
            name='spells_collection',
            field=models.ManyToManyField(blank=True, to='collector.PathfinderSpellsCollection'),
        ),
    ]
