# Generated by Django 4.0 on 2022-08-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0122_alter_pathfinderlevel_spells_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderrace',
            name='speed',
        ),
    ]
