# Generated by Django 4.0 on 2022-08-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0124_pathfinderskill_acp_sensistive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathfinderskill',
            old_name='acp_sensistive',
            new_name='acp_applies',
        ),
    ]
