# Generated by Django 4.0 on 2022-08-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0125_rename_acp_sensistive_pathfinderskill_acp_applies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderlevel',
            name='caster_level',
            field=models.IntegerField(default=20),
        ),
    ]
