# Generated by Django 4.0 on 2022-08-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0126_pathfinderlevel_caster_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderclass',
            name='caster_level',
            field=models.IntegerField(default=20),
        ),
    ]
