# Generated by Django 4.0 on 2022-08-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0127_pathfinderclass_caster_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathfinderlevel',
            name='caster_level',
        ),
    ]
