# Generated by Django 4.0 on 2022-08-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0129_pathfinderclass_uses_custom_spells_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderspellscollection',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
