# Generated by Django 4.0 on 2022-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0130_pathfinderspellscollection_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderlevel',
            name='custom_fields',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
