# Generated by Django 4.0 on 2022-08-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0131_pathfinderlevel_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='in_spotlight',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
