# Generated by Django 4.0 on 2022-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0132_pathfindercharacter_in_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfindercharacter',
            name='next_level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
