# Generated by Django 4.0 on 2022-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0133_pathfindercharacter_next_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderlevel',
            name='spellcasting_ability',
            field=models.CharField(blank=True, choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('---', 'None')], default='---', max_length=3),
        ),
    ]
