# Generated by Django 4.0 on 2022-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0134_pathfinderlevel_spellcasting_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderfeat',
            name='is_metamagic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathfinderfeat',
            name='is_save_related',
            field=models.BooleanField(default=False),
        ),
    ]
