# Generated by Django 4.0 on 2022-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0135_pathfinderfeat_is_metamagic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathfinderfeat',
            name='is_item_creation',
            field=models.BooleanField(default=False),
        ),
    ]
